import numpy as np

def load_flow_dataset(file_path):
    """Loads the Flow Free dataset generated by Jules."""
    data = np.load(file_path, allow_pickle=True)
    return data['puzzles'], data['solutions'], data['metadata']

def visualize_flow(grid):
    """Prints the Flow Free grid with ANSI colors for easy debugging."""
    # Mapping IDs to terminal colors
    colors = {
        0: "\033[0m . ", # Empty
        1: "\033[91m 1 ", # Red
        2: "\033[92m 2 ", # Green
        3: "\033[94m 3 ", # Blue
        4: "\033[93m 4 ", # Yellow
        5: "\033[95m 5 ", # Magenta
        6: "\033[96m 6 ", # Cyan
        7: "\033[31m 7 ", # Dark Red
        8: "\033[32m 8 ", # Dark Green
        9: "\033[34m 9 ", # Dark Blue
        10: "\033[33m 10 ", # Dark Yellow
        11: "\033[35m 11 ", # Dark Magenta
        12: "\033[36m 12 ", # Dark Cyan
        13: "\033[97m 13 ", # White
        14: "\033[90m 14 ", # Gray
        15: "\033[37m 15 ", # Light Gray
    }

    print("-" * (len(grid) * 3))
    for row in grid:
        line = "".join([colors.get(cell, f" {cell} ") for cell in row])
        print(line + "\033[0m")
    print("-" * (len(grid) * 3))

# Example Usage for Jules to include:
# puzzles, solutions, meta = load_flow_dataset('outputs/flow_8x8_hard.npz')
# print(f"Difficulty: {meta[0]['difficulty']}")
# visualize_flow(puzzles[0])   # Shows the start
# visualize_flow(solutions[0]) # Shows the full path
